export const eventData =  [
    {
        "id" : "1",
        "name" : "Tipod Podcast",
        "img" : "https://res.cloudinary.com/dehaxoyib/image/upload/c_fill,h_634,w_730/v1584604270/55804589f5c9882084ac87ce305cd8d6_jssepz.jpg",
        "price" : "0",
        "status": "OPEN",
        "location" : "UPH MEDAN CAMPUS",
        "date" : "3 March 2020",
        "description" : "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum ullamcorper facilisis eros eu commodo. Sed tristique aliquet nunc. Nam ut fringilla turpis, laoreet fringilla nisi. Sed varius augue in vehicula bibendum. Suspendisse a dolor velit. Proin sed orci molestie, malesuada sem id, auctor sem. Praesent suscipit sit amet odio tempus fermentum. Quisque vel erat elementum, condimentum nisl et, tincidunt enim. Phasellus tincidunt leo elit. Quisque auctor lacinia diam, a tincidunt magna faucibus euismod. Aenean laoreet accumsan iaculis. Mauris non ex dignissim, lacinia tortor vitae, condimentum velit. Integer non finibus nunc. Proin odio turpis, efficitur nec dictum vel, tincidunt ut lectus. In at diam accumsan, ullamcorper mi ut, tincidunt elit. In egestas eros augue, non consequat mi facilisis sit amet. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.",
        "slot" : "10",
        "hostName" : "Partic",
        "hostUsername" : "@ParticINC."
    },
    {
        "id" : "2",
        "name" : "Tipod Podcast",
        "img" : "https://res.cloudinary.com/dehaxoyib/image/upload/c_fill,h_634,w_730/v1584604270/55804589f5c9882084ac87ce305cd8d6_jssepz.jpg",
        "price" : "10000",
        "status ": "SOLD",
        "location" : "UPH MEDAN CAMPUS",
        "date" : "3 March 2020",
        "description" : "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum ullamcorper facilisis eros eu commodo. Sed tristique aliquet nunc. Nam ut fringilla turpis, laoreet fringilla nisi. Sed varius augue in vehicula bibendum. Suspendisse a dolor velit. Proin sed orci molestie, malesuada sem id, auctor sem. Praesent suscipit sit amet odio tempus fermentum. Quisque vel erat elementum, condimentum nisl et, tincidunt enim. Phasellus tincidunt leo elit. Quisque auctor lacinia diam, a tincidunt magna faucibus euismod. Aenean laoreet accumsan iaculis. Mauris non ex dignissim, lacinia tortor vitae, condimentum velit. Integer non finibus nunc. Proin odio turpis, efficitur nec dictum vel, tincidunt ut lectus. In at diam accumsan, ullamcorper mi ut, tincidunt elit. In egestas eros augue, non consequat mi facilisis sit amet. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.",
        "slot" : "10",
        "hostName" : "Partic",
        "hostUsername" : "@ParticINC."
    },
    {
        "id" : "3",
        "name" : "Tipod Podcast",
        "img" : "https://res.cloudinary.com/dehaxoyib/image/upload/c_fill,h_634,w_730/v1584604270/55804589f5c9882084ac87ce305cd8d6_jssepz.jpg",
        "price" : "0",
        "status": "OPEN",
        "location" : "UPH MEDAN CAMPUS",
        "date" : "3 March 2020",
        "description" : "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum ullamcorper facilisis eros eu commodo. Sed tristique aliquet nunc. Nam ut fringilla turpis, laoreet fringilla nisi. Sed varius augue in vehicula bibendum. Suspendisse a dolor velit. Proin sed orci molestie, malesuada sem id, auctor sem. Praesent suscipit sit amet odio tempus fermentum. Quisque vel erat elementum, condimentum nisl et, tincidunt enim. Phasellus tincidunt leo elit. Quisque auctor lacinia diam, a tincidunt magna faucibus euismod. Aenean laoreet accumsan iaculis. Mauris non ex dignissim, lacinia tortor vitae, condimentum velit. Integer non finibus nunc. Proin odio turpis, efficitur nec dictum vel, tincidunt ut lectus. In at diam accumsan, ullamcorper mi ut, tincidunt elit. In egestas eros augue, non consequat mi facilisis sit amet. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.",
        "slot" : "10",
        "hostName" : "Partic",
        "hostUsername" : "@ParticINC."
    },
    {
        "id" : "4",
        "name" : "Tipod Podcast",
        "img" : "https://res.cloudinary.com/dehaxoyib/image/upload/c_fill,h_634,w_730/v1584604270/55804589f5c9882084ac87ce305cd8d6_jssepz.jpg",
        "price" : "100000",
        "status": "SOLD",
        "location" : "UPH MEDAN CAMPUS",
        "date" : "3 March 2020",
        "description" : "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum ullamcorper facilisis eros eu commodo. Sed tristique aliquet nunc. Nam ut fringilla turpis, laoreet fringilla nisi. Sed varius augue in vehicula bibendum. Suspendisse a dolor velit. Proin sed orci molestie, malesuada sem id, auctor sem. Praesent suscipit sit amet odio tempus fermentum. Quisque vel erat elementum, condimentum nisl et, tincidunt enim. Phasellus tincidunt leo elit. Quisque auctor lacinia diam, a tincidunt magna faucibus euismod. Aenean laoreet accumsan iaculis. Mauris non ex dignissim, lacinia tortor vitae, condimentum velit. Integer non finibus nunc. Proin odio turpis, efficitur nec dictum vel, tincidunt ut lectus. In at diam accumsan, ullamcorper mi ut, tincidunt elit. In egestas eros augue, non consequat mi facilisis sit amet. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.",
        "slot" : "10",
        "hostName" : "Partic",
        "hostUsername" : "@ParticINC."
    },
    {
        "id" : "5",
        "name" : "Tipod Podcast",
        "img" : "https://res.cloudinary.com/dehaxoyib/image/upload/c_fill,h_634,w_730/v1584604270/55804589f5c9882084ac87ce305cd8d6_jssepz.jpg",
        "price" : "0",
        "status": "OPEN",
        "location" : "UPH MEDAN CAMPUS",
        "date" : "3 March 2020",
        "description" : "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum ullamcorper facilisis eros eu commodo. Sed tristique aliquet nunc. Nam ut fringilla turpis, laoreet fringilla nisi. Sed varius augue in vehicula bibendum. Suspendisse a dolor velit. Proin sed orci molestie, malesuada sem id, auctor sem. Praesent suscipit sit amet odio tempus fermentum. Quisque vel erat elementum, condimentum nisl et, tincidunt enim. Phasellus tincidunt leo elit. Quisque auctor lacinia diam, a tincidunt magna faucibus euismod. Aenean laoreet accumsan iaculis. Mauris non ex dignissim, lacinia tortor vitae, condimentum velit. Integer non finibus nunc. Proin odio turpis, efficitur nec dictum vel, tincidunt ut lectus. In at diam accumsan, ullamcorper mi ut, tincidunt elit. In egestas eros augue, non consequat mi facilisis sit amet. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.",
        "slot" : "10",
        "hostName" : "Partic",
        "hostUsername" : "@ParticINC."
    },
    {
        "id" : "6",
        "name" : "Tipod Podcast",
        "img" : "https://res.cloudinary.com/dehaxoyib/image/upload/c_fill,h_634,w_730/v1584604270/55804589f5c9882084ac87ce305cd8d6_jssepz.jpg",
        "price" : "10000",
        "status ": "SOLD",
        "location" : "UPH MEDAN CAMPUS",
        "date" : "3 March 2020",
        "hostName" : "Partic",
        "hostUsername" : "@ParticINC."
    },
    {
        "id" : "7",
        "name" : "Tipod Podcast",
        "img" : "https://res.cloudinary.com/dehaxoyib/image/upload/c_fill,h_634,w_730/v1584604270/55804589f5c9882084ac87ce305cd8d6_jssepz.jpg",
        "price" : "0",
        "description" : "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum ullamcorper facilisis eros eu commodo. Sed tristique aliquet nunc. Nam ut fringilla turpis, laoreet fringilla nisi. Sed varius augue in vehicula bibendum. Suspendisse a dolor velit. Proin sed orci molestie, malesuada sem id, auctor sem. Praesent suscipit sit amet odio tempus fermentum. Quisque vel erat elementum, condimentum nisl et, tincidunt enim. Phasellus tincidunt leo elit. Quisque auctor lacinia diam, a tincidunt magna faucibus euismod. Aenean laoreet accumsan iaculis. Mauris non ex dignissim, lacinia tortor vitae, condimentum velit. Integer non finibus nunc. Proin odio turpis, efficitur nec dictum vel, tincidunt ut lectus. In at diam accumsan, ullamcorper mi ut, tincidunt elit. In egestas eros augue, non consequat mi facilisis sit amet. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.",
        "slot" : "10",
        "status": "OPEN",
        "location" : "UPH MEDAN CAMPUS",
        "date" : "3 March 2020",
        "hostName" : "Partic",
        "hostUsername" : "@ParticINC."
    },
    {
        "id" : "8",
        "name" : "Tipod Podcast",
        "img" : "https://res.cloudinary.com/dehaxoyib/image/upload/c_fill,h_634,w_730/v1584604270/55804589f5c9882084ac87ce305cd8d6_jssepz.jpg",
        "price" : "100000",
        "status": "SOLD",
        "description" : "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum ullamcorper facilisis eros eu commodo. Sed tristique aliquet nunc. Nam ut fringilla turpis, laoreet fringilla nisi. Sed varius augue in vehicula bibendum. Suspendisse a dolor velit. Proin sed orci molestie, malesuada sem id, auctor sem. Praesent suscipit sit amet odio tempus fermentum. Quisque vel erat elementum, condimentum nisl et, tincidunt enim. Phasellus tincidunt leo elit. Quisque auctor lacinia diam, a tincidunt magna faucibus euismod. Aenean laoreet accumsan iaculis. Mauris non ex dignissim, lacinia tortor vitae, condimentum velit. Integer non finibus nunc. Proin odio turpis, efficitur nec dictum vel, tincidunt ut lectus. In at diam accumsan, ullamcorper mi ut, tincidunt elit. In egestas eros augue, non consequat mi facilisis sit amet. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.",
        "slot" : "10",
        "location" : "UPH MEDAN CAMPUS",
        "date" : "3 March 2020",
        "hostName" : "Partic",
        "hostUsername" : "@ParticINC."
    }
]

