export const ticketData =  [
    {
        id : "1",
        name : 'Partic Event',
        date : '3 March 2020',
        time : '19:00 - End',
        status : 'attended',
        location : 'UPH Medan Campus',
        qty : '3',
        img : '',
    },
    {
        id : "2",
        name : 'Partic Event',
        date : '3 March 2020',
        time : '19:00 - End',
        status : 'expired',
        location : 'UPH Medan Campus',
        qty : '1',
        img : '',
    },
    {
        id : "3",
        name : 'Partic Event',
        date : '3 March 2020',
        time : '19:00 - End',
        location : 'UPH Medan Campus',
        status : 'not attended yet',
        qty : '2',
        img : '',
    },
]